version: '3.8'

services:
  app:
    build:
      context: .
    container_name: dearus-app
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dearus-net

  mysql:
    image: mysql:8.0
    container_name: dearus-db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - dearus-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:

networks:
  dearus-net: